#!/usr/bin/env python3
"""Generate a stress test for deferrable notes.

Usage: test/gen-stress.py SEED [block] > test/stress-SEED[b].tex

The document is sixty random paragraphs of lipsum with commentary notes
(\\ltnote, deferrable, of random length, some in vertical mode) and
footnotes in the margin (\\fn), crowded enough that plain marginfix moves
many footnotes off their page.  With "block", some paragraphs are followed
by a rule set with \\blockmargin, so that the margin has several pieces.
See prioritycheck.tex for the checks.
"""
import random
import sys

seed = int(sys.argv[1]) if len(sys.argv) > 1 else 1
blocks = len(sys.argv) > 2 and sys.argv[2] == "block"
r = random.Random(seed)

out = [r"""%% Generated by: test/gen-stress.py %d%s
\documentclass[a4paper]{memoir}
\setlrmarginsandblock{2cm}{6cm}{*}
\setmarginnotes{1em}{4.5cm}{1em}
\checkandfixthelayout
\usepackage{marginfix}
\footnotesinmargin
\usepackage{lipsum}
\input{test/prioritycheck}
\begin{document}
\chapter{Stress}""" % (seed, " block" if blocks else "")]


def lip(a, b):
    p = r.randint(1, 50)
    return r"\lipsum*[%d][%d-%d]" % (p, a, b)


for i in range(60):
    parts = []
    if r.random() < 0.15:
        out.append(r"\ltnote{%s}" % lip(1, r.choice([3, 8, 14])))
    for s in range(r.randint(2, 6)):
        parts.append(lip(1, r.randint(2, 4)))
        x = r.random()
        if x < 0.10:
            n = r.choice([2, 3, 5, 8, 12, 16])
            parts.append(r"\ltnote{%s}" % lip(1, n))
        elif x < 0.24:
            parts.append(r"\fn{%s}" % lip(1, r.randint(1, 3)))
    if blocks and r.random() < 0.08:
        out.append(r"\blockmargin\noindent\rule{\textwidth}{%dpt}\unblockmargin"
                   % r.choice([40, 120]))
    if r.random() < 0.1:
        out.append(r"\section{S%d}" % i)
    out.append(" ".join(parts) + "\n")
out.append(r"\end{document}")
print("\n".join(out))
